-- client/modules/vehicle/manager/commands.lua
-- FIX: Ce fichier est intentionnellement vide.
-- Les commandes véhicules sont dans client/modules/commands/manager/vehicle.lua
-- pour éviter les doublons.
