-- bridge/client/kt_interact_editor.lua
-- FIX: Ce fichier était une copie identique de kt_interact_data.lua causant un double
-- enregistrement de Bridge.InteractData et un conflit de bridges.
-- La fusion kt_interact_data + kt_interact_editor est entièrement gérée dans
-- bridge/client/kt_interact_data.lua qui pointe déjà sur la ressource "kt_interact".
-- Ce fichier est conservé vide pour compatibilité avec fxmanifest.lua.
