-- client/modules/vehicle/commands.lua
-- FIX #5 : ce fichier est intentionnellement vide.
--           Les commandes /myvehicles et /spawncar étaient dupliquées ici
--           ET dans client/modules/commands/vehicle.lua.
--           La version dans commands/vehicle.lua est complète et correcte.
--           Ce fichier n'est plus chargé dans fxmanifest.lua.